# @package agent
_target_: agent.baku.BCAgent
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
hidden_dim: ${suite.hidden_dim}
stddev_schedule: 0.1
stddev_clip: 0.3
use_tb: ${use_tb}
augment: True
obs_type: ${obs_type}
encoder_type: ${encoder_type}
policy_type: ${policy_type}
policy_head: ${policy_head}
pixel_keys: ${suite.pixel_keys}
proprio_key: ${suite.proprio_key}
feature_key: ${suite.feature_key}
use_proprio: ${use_proprio}
train_encoder: true
norm: false
history: ${suite.history}
history_len: ${suite.history_len}
eval_history_len: ${suite.eval_history_len}
separate_encoders: false # have a separate encoder for each pixel key
temporal_agg: ${temporal_agg}
max_episode_len: ${suite.task_make_fn.max_episode_len}
num_queries: ${num_queries}
use_language: ${use_language}
use_actions: ${use_actions}
prompt: ${prompt}
film: true
