# @package suite
defaults:
  - _self_
  - task: xarm_env

suite: xarm_env
name: "xarm_env"

# task settings
frame_stack: 1
action_repeat: 1
discount: 0.99
hidden_dim: 256

# train settings
num_train_steps: 601000
log_every_steps: 1000
save_every_steps: 50000
history: false
history_len: 10

# eval
eval_every_steps: 200000
num_eval_episodes: 5
eval_history_len: 5

# data loading
action_after_steps: 1 #8

# obs_keys
pixel_keys: ["pixels0", "pixels1", "pixels4", "pixels5"]
proprio_key: "proprioceptive"
feature_key: "features"

# snapshot
save_snapshot: true

task_make_fn:
  _target_: suite.xarm_env.make
  # suite: ${suite.task.suite}
  # scenes: ${suite.task.scenes}
  # tasks: ${suite.task.tasks}
  frame_stack: ${suite.frame_stack}
  action_repeat: ${suite.action_repeat}
  seed: ${seed}
  height: 128
  width: 128
  max_episode_len: ??? # to be specified later
  max_state_dim: ??? # to be specified later
  use_egocentric: false
  task_description: "just training"
  pixel_keys: ${suite.pixel_keys}
  eval: ${eval} # eval true mean use robot
